### ISSUE TITLE
"There was a problem authorizing with Eventbrite"

### ISSUE THREAD

**Issue by adamsoffer** [beaulebens/keyring#23] opened 2017-09-06 14:28 UTC
![image](https://user-images.githubusercontent.com/555740/30117455-4153bb5e-92ee-11e7-80e3-94308c3ddd66.png)

I'm getting this error when trying to authorize eventbrite. The api key and secret are definitely correct. Any idea what's going on here?

**Comment by ads1018** [comment] 2017-09-06 16:51
I suspect this is an issue related to ssl. I'm making a request from https

**Comment by beaulebens** [comment] 2019-11-28 00:33
I've confirmed that the Eventbrite service works for me over https, so I'm closing this unless there's more info to help debug.

**Closed by beaulebens** 2019-11-28 00:33 UTC
