### ISSUE TITLE
Put the repo on a diet

### ISSUE THREAD

**Issue by mdrovdahl** [beaulebens/keyring#67] opened 2020-03-11 02:55 UTC
I just cloned the repo on a new machine, over a semi-slow broadband connection and was surprised to find the repo weighs in at 158MB.

I'm no git expert, but it looks like the bulk of this is in the `.git/objects/` directory and could maybe be cleaned up / trimmed down? 

Refs:
* https://stackoverflow.com/questions/2116778/reduce-git-repository-size
* https://github.com/18F/C2/issues/439#issuecomment-461915807 which surfaces such commits as https://github.com/beaulebens/keyring/commit/c54e474c0b33e804edd726eee72f4aa9172ae105 and may be related to #8

**Comment by sanmai** [comment] 2020-10-13 14:39
Possible duplicate of #8

**Comment by beaulebens** [comment] 2021-02-28 19:27
This is because of something weird that happened when I originally brought this over from WP.org's SVN. It somehow included the entire history of every plugin (weeeeee!).

I just found this which seems to be what I want https://passingcuriosity.com/2017/truncating-git-history/ -- just need to figure out the first relevant commit and give it a try.

**Closed** 2021-02-28 19:39 UTC

**Comment by mdrovdahl** [comment] 2021-03-01 05:00
Just did a fresh checkout (cheers for the 3.0 release)...not sure if this is the expected outcome from https://github.com/beaulebens/keyring/commit/1cc7bb4c6dbe8de38b1c74ec370d83e7b6cc739f, but for reference here's what I see:

```
markd@XPS-9310:~/dev$ git clone git@github.com:beaulebens/keyring.git
Cloning into 'keyring'...
remote: Enumerating objects: 283, done.
remote: Counting objects: 100% (283/283), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 970441 (delta 95), reused 271 (delta 89), pack-reused 970158
Receiving objects: 100% (970441/970441), 131.54 MiB | 2.40 MiB/s, done.
Resolving deltas: 100% (413094/413094), done.
markd@XPS-9310:~/dev$ du -hs keyring/.git/*
4.0K	keyring/.git/branches
4.0K	keyring/.git/config
4.0K	keyring/.git/description
4.0K	keyring/.git/HEAD
60K	keyring/.git/hooks
8.0K	keyring/.git/index
8.0K	keyring/.git/info
32K	keyring/.git/logs
158M	keyring/.git/objects
4.0K	keyring/.git/packed-refs
28K	keyring/.git/refs
markd@XPS-9310:~/dev$ du -hs keyring/.git/objects/pack/*
26M	keyring/.git/objects/pack/pack-dcf4da87be254d6ec557bafad2cd3da2242e29e2.idx
132M	keyring/.git/objects/pack/pack-dcf4da87be254d6ec557bafad2cd3da2242e29e2.pack
```
